[package]
name = "sentencepiece-bpe-tokenizer"
version = "0.1.0"
edition = "2021"

[lib]
name = "sb_tokenizer_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
