[package]
name = "sentencepiece-bpe-tokenizer"
version = "0.1.0"
edition = "2021"

[lib]
name = "sb_tokenizer"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25", features = ["extension-module"] }
