[project]
# 项目根目录
root = "."

# 虚拟环境目录
venv = ".venv"

# Python 版本
python = "3.12"

# 构建工具
build-system = "setuptools"

# 开发依赖
dev-dependencies = [
    "pytest>=7.0",
    "black>=23.0",
    "mypy>=1.0",
]
